function(assemble_rule target)
    set(inputVar "${ASSEMBLER_PRE};-g;-mprocessor=ATSAMD21J18A;-Wa,--defsym=__MPLAB_BUILD=1,${MP_EXTRA_AS_POST};-mdfp=C:/Users/silenteagle/.mchp_packs/Microchip/SAMD21_DFP/3.6.144/samd21a")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
function(assembleWithPreprocess_rule target)
    set(inputVar "${MP_EXTRA_AS_PRE};-g;-mprocessor=ATSAMD21J18A;-DXPRJ_default=default;-Wa,--defsym=__MPLAB_BUILD=1,${MP_EXTRA_AS_POST}")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
function(compile_rule target)
    set(inputVar "${CC_PRE};-g;-x;c;-c;-mprocessor=ATSAMD21J18A;-ffunction-sections;-fdata-sections;-O1;-fno-common;-I../../../../src;-I../../../../src/config/default;-I../../../../src/config/default/system/fs/fat_fs/file_system;-I../../../../src/config/default/system/fs/fat_fs/hardware_access;-I../../../../src/packs/ATSAMD21J18A_DFP;-I../../../../src/packs/CMSIS;-I../../../../src/packs/CMSIS/CMSIS/Core/Include;-Werror;-Wall;${INSTRUMENTED_TRACE_OPTIONS};${FUNCTION_LEVEL_PROFILING_OPTIONS};-DXPRJ_default=default;-mdfp=C:/Users/silenteagle/.mchp_packs/Microchip/SAMD21_DFP/3.6.144/samd21a;${CMSIS_PACK_INCLUDE}")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
function(compile_cpp_rule target)
    set(inputVar "${CC_PRE};-g;-mprocessor=ATSAMD21J18A;-frtti;-fexceptions;-fno-check-new;-fenforce-eh-specs;-ffunction-sections;-O1;-fno-common;-I../../../../src;-I../../../../src/config/default;-I../../../../src/config/default/system/fs/fat_fs/file_system;-I../../../../src/config/default/system/fs/fat_fs/hardware_access;-I../../../../src/packs/ATSAMD21J18A_DFP;-I../../../../src/packs/CMSIS;-I../../../../src/packs/CMSIS/CMSIS/Core/Include;${INSTRUMENTED_TRACE_OPTIONS};${FUNCTION_LEVEL_PROFILING_OPTIONS};-DXPRJ_default=default;-mdfp=C:/Users/silenteagle/.mchp_packs/Microchip/SAMD21_DFP/3.6.144/samd21a;${CMSIS_PACK_INCLUDE}")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
function(link_rule target)
    set(inputVar "${MP_EXTRA_LD_PRE};-g;-mprocessor=ATSAMD21J18A;-mno-device-startup-code;${INSTRUMENTED_TRACE_OPTIONS};${FUNCTION_LEVEL_PROFILING_OPTIONS};-DXPRJ_default=default;-Wl,--defsym=__MPLAB_BUILD=1,${MP_EXTRA_LD_POST},${MP_LINKER_FILE_OPTION},--defsym=_min_heap_size=512,,--memorysummary,memoryfile.xml;-mdfp=C:/Users/silenteagle/.mchp_packs/Microchip/SAMD21_DFP/3.6.144/samd21a")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_link_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
