name: HelloCIWorld-SAMD

on: [push]

jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
    - name: run static analysis
      run: cppcheck --quiet --error-exitcode=1 --project=.cppcheck
    - name: generate-makefiles
      run: prjMakefilesGenerator.bat cicd_project.X
    - name: clean
      run: make -j4 -C cicd_project.X clean
    - name: make
      run: make -j4 -C cicd_project.X
    - uses: actions/upload-artifact@v4
      with:
        name: noEthBuild_$.$_$.zip
        path: cicd_project.X/dist/default/production
